image: $BUILD_IMAGE

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - git submodule update --init --recursive
        - git clone https://gitlab.com/mikegerwitz/hoxsl
        - export SAXON_CP=/usr/share/ant/lib/saxon9/saxon9he.jar
        - export HOXSL=hoxsl
        - ./bootstrap
        - make all check info pdf html
    artifacts:
        paths:
            - doc/
            - tamer/target
        expire_in: 30 min

pages:
    stage: deploy
    script:
        - mkdir -p public/doc
        - mv doc/tame.html/* doc/tame.pdf doc/tame.info public/
    artifacts:
        paths:
            - public/
        expire_in: 30 min
    only:
        - tags
