#!/bin/bash
# Bootstrap from source repository
#
#   Copyright (C) 2014-2021 Ryan Specialty Group, LLC.
#
#  This file is part of TAME.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This script should be run _once_ after an initial checkout, otherwise it
# may overwrite any subsequent configuration you may have done.
##

set -euo pipefail

# This will apply a default configuration, which will be used to perform a
# fetch of the dependencies.  You are of course free to reconfigure after.
./autogen.sh && ./configure && make fetch

