[package]
name = "tamer"
version = "0.0.0"
authors = ["Mike Gerwitz <mike.gerwitz@ryansg.com>"]
description="TAME in Rust"
license="GPLv3+"
edition = "2018"

[profile.dev]
# Release-level optimizations.  Spending the extra couple of moments
# compile-time is well worth the huge savings we get at runtime.  Note that
# this is still every so slightly slower than a release build; see other
# profile options for release at
# <https://doc.rust-lang.org/cargo/reference/manifest.html>.
opt-level = 3

[profile.release]
lto = true

[profile.bench]
# We want our benchmarks to be representative of how well TAME will perform
# in a release.
lto = true

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"

[dependencies]
bumpalo = ">= 2.6.0"
# used by petgraph
fixedbitset = ">= 0.1"
fxhash = ">= 0.2.1"
petgraph = ">= 0.4.13"
quick-xml = ">= 0.17.0"
getopts = "0.2"
exitcode = "1.1.2"

