#!/usr/bin/env bash
#
# Runner script system test
#
#  Copyright (C) 2014-2023 Ryan Specialty, LLC.
#
#  This file is part of TAME.
#
#  TAME is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -euo pipefail

cd "$( dirname "$0" )"

declare -r bin=../bin

run-test()
{
    "$bin"/runner _stub/program.js "$@" >/dev/null
}

expect-ok()
{
    run-test "$@"
}

expect-fail()
{
    run-test "$@" && exit 1 || true
}

main() {
  set -x

  # should succeed
  expect-ok _stub/good.yml

  # should fail
  expect-fail _stub/bad.yml

  # concatenation of good and bad should fail
  expect-fail _stub/{good,bad}.yml

  # missing file should fail
  expect-fail does-not-exist.yml 2>/dev/null
}

main "$@"
