#!/bin/bash
# Configuration script to be run before `make'
#
#   Copyright (C) 2014-2020 Ryan Specialty Group, LLC.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

set -euo pipefail

echo "Generating suppliers.mk..."
# TODO: kluge; do properly.
rm -f suppliers.mk
make suppliers.mk

# XXX: paths are hard-coded here!
while read csv; do
  csvbase="${csv%%.*}"
  echo "$csvbase.xmlo: $csvbase.xml"
  echo "$csvbase.xml: $csvbase.csvo"
done < <( find "$@" -regex '^.+\.csv.?$' ) \
  >> suppliers.mk

while read tdat; do
  tbase="${tdat%%.*}"
  echo "$tbase.xmlo: $tbase.xml rater/core/tdat.xmlo"
  echo "$tbase.xml: $tdat"
  echo -e "\trater/tools/tdat2xml \$< > \$@"
done < <( find "$@" -regex '^.+territories/.+\.dat$' ) \
  >> suppliers.mk

