\input texinfo
@c  This document is part of the TAME manual.
@c  Copyright (C) 2015, 2016 LoVullo Associates, Inc.
@c    Permission is granted to copy, distribute and/or modify this document
@c    under the terms of the GNU Free Documentation License, Version 1.3 or
@c    any later version published by the Free Software Foundation; with no
@c    Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
@c    A copy of the license is included in the section entitled ``GNU Free
@c    Documentation License''.

@include version.texi

@c %**start of header
@setfilename tame.info
@documentencoding UTF-8
@settitle TAME Manual v@value{VERSION}
@c %**end of header

@copying
This manual is for TAME, version @value{VERSION}.

Copyright @copyright{} 2015, 2016 LoVullo Associates, Inc.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
@end quotation

@end copying


@titlepage
@title TAME Manual v@value{VERSION}
@author Mike Gerwitz, LoVullo Associates

@c  Start copyright page
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Main
@end ifnottex

@menu
* Preprocessor::      Metaprogramming system
* Dependency Graph::  Dependency processing and flow analysis
* Symbol Table::      Lookup table for all objects
* License::           Document License
@end menu

@ifnottex
@insertcopying
@end ifnottex


@c TODO: move me
@macro mdash{}
---
@end macro

@macro todo{str}
@emph{[@strong{TODO: }\str\]}
@end macro

@macro ttref{ref}
@ref{\ref\,,@code{\ref\}}
@end macro

@macro proof{str}
@sc{Proof:} \str\ @qed
@end macro

@macro qed{}
∎
@end macro

@ifhtml
@c override @math to delimit for MathJax/KaTeX/etc
@definfoenclose math,\(,\)
@end ifhtml


@node Preprocessor
@chapter Preprocessor

@menu
* Macro Expansion::
@end menu

@node Macro Expansion
@section Macro Expansion

@menu
* Expansion Sequence::
@end menu

@lowersections
@include ../src/preproc/expand/expand-sequence.texi
@raisesections

@c chapter
@raisesections
@include ../src/graph.texi
@include ../src/symtable.texi
@lowersections

@include license.texi

@bye
